// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    MessageContent: typeof import('./components/MessageContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabButton: typeof import('./components/TabButton.vue')['default']
    TabWrapper: typeof import('./components/TabWrapper.vue')['default']
    TheArchive: typeof import('./components/TheArchive.vue')['default']
    TheEditor: typeof import('./components/TheEditor.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
  }
}
